import { createFileRoute } from "@tanstack/react-router";
import { CircleDot, GitMerge, Rocket, TestTube2, Wrench } from "lucide-react";
import { toast } from "sonner";

import { AppShell } from "@/components/layout/app-shell";
import { SectionCard, StatusPill } from "@/components/primitives";
import { StatCard } from "@/components/stat-card";
import { Button } from "@/components/ui/button";
import { pullRequests } from "@/lib/mock-data";

export const Route = createFileRoute("/remediation")({
  head: () => ({
    meta: [
      { title: "Remediation Center — SentinelAI" },
      {
        name: "description",
        content: "Automated dependency upgrades with pull request status, test results and deployment tracking.",
      },
      { property: "og:title", content: "Remediation Center — SentinelAI" },
      { property: "og:description", content: "Automated upgrade pull requests, tests and deployments in one view." },
    ],
  }),
  component: RemediationPage,
});

const statusTone = {
  merged: "healthy",
  open: "info",
  "checks-failed": "critical",
  queued: "neutral",
} as const;

const testTone = { passed: "healthy", failed: "critical", running: "warning" } as const;
const deployTone = { deployed: "healthy", staged: "info", pending: "neutral" } as const;

function RemediationPage() {
  return (
    <AppShell
      title="Remediation center"
      description="Suggested upgrades, automated pull requests and their journey to production."
      actions={
        <Button className="gap-2 rounded-xl" onClick={() => toast.success("Remediation run started", { description: "12 upgrade candidates queued." })}>
          <Wrench className="size-4" /> Run auto-remediation
        </Button>
      }
    >
      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <StatCard index={0} label="Open upgrade PRs" value={3} icon={CircleDot} tone="info" />
        <StatCard index={1} label="Merged this month" value={38} delta={12} icon={GitMerge} tone="healthy" />
        <StatCard index={2} label="Checks passing" value={86} suffix="%" icon={TestTube2} tone="primary" />
        <StatCard index={3} label="Deployed fixes" value={31} icon={Rocket} tone="ai" />
      </div>

      <SectionCard className="mt-4" title="Automated pull requests" description="Generated by the SentinelAI remediation bot.">
        <div className="space-y-3">
          {pullRequests.map((pr, i) => (
            <article
              key={pr.id}
              className="animate-[var(--animate-fade-up)] rounded-2xl border border-border p-4 transition-shadow hover:shadow-[var(--shadow-card)]"
              style={{ animationDelay: `${i * 50}ms` }}
            >
              <div className="flex flex-wrap items-start justify-between gap-3">
                <div className="min-w-0">
                  <p className="truncate text-sm font-medium">{pr.title}</p>
                  <p className="mt-0.5 text-xs text-muted-foreground">
                    {pr.repo} · opened {pr.age} ago by {pr.author}
                  </p>
                </div>
                <StatusPill tone={statusTone[pr.status]}>{pr.status.replace("-", " ")}</StatusPill>
              </div>

              <div className="mt-3 flex flex-wrap items-center gap-2">
                <span className="rounded-lg bg-muted px-2 py-1 font-mono text-[11px]">{pr.from}</span>
                <span className="text-muted-foreground">→</span>
                <span className="rounded-lg bg-healthy/12 px-2 py-1 font-mono text-[11px] text-healthy">{pr.to}</span>
                <StatusPill tone={testTone[pr.tests]}><TestTube2 className="size-3" /> tests {pr.tests}</StatusPill>
                <StatusPill tone={deployTone[pr.deploy]}><Rocket className="size-3" /> {pr.deploy}</StatusPill>
                <StatusPill tone={pr.risk === "high" ? "critical" : pr.risk === "medium" ? "warning" : "healthy"}>
                  {pr.risk} change risk
                </StatusPill>
                <div className="ml-auto flex gap-2">
                  <Button size="sm" variant="ghost" onClick={() => toast("Opening diff…")}>View diff</Button>
                  <Button size="sm" className="rounded-lg" disabled={pr.status === "merged"} onClick={() => toast.success("Merge queued")}>
                    Merge
                  </Button>
                </div>
              </div>
            </article>
          ))}
        </div>
      </SectionCard>
    </AppShell>
  );
}
