/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlastRadiusRouteImport } from './routes/blast-radius'
import { Route as DependenciesRouteImport } from './routes/dependencies'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RemediationRouteImport } from './routes/remediation'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RepositoriesRouteImport } from './routes/repositories'
import { Route as SbomRouteImport } from './routes/sbom'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as VulnerabilitiesRouteImport } from './routes/vulnerabilities'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlastRadiusRoute = BlastRadiusRouteImport.update({
  id: '/blast-radius',
  path: '/blast-radius',
  getParentRoute: () => rootRouteImport,
} as any)
const DependenciesRoute = DependenciesRouteImport.update({
  id: '/dependencies',
  path: '/dependencies',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RemediationRoute = RemediationRouteImport.update({
  id: '/remediation',
  path: '/remediation',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoriesRoute = RepositoriesRouteImport.update({
  id: '/repositories',
  path: '/repositories',
  getParentRoute: () => rootRouteImport,
} as any)
const SbomRoute = SbomRouteImport.update({
  id: '/sbom',
  path: '/sbom',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const VulnerabilitiesRoute = VulnerabilitiesRouteImport.update({
  id: '/vulnerabilities',
  path: '/vulnerabilities',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blast-radius': typeof BlastRadiusRoute
  '/dependencies': typeof DependenciesRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/remediation': typeof RemediationRoute
  '/reports': typeof ReportsRoute
  '/repositories': typeof RepositoriesRoute
  '/sbom': typeof SbomRoute
  '/settings': typeof SettingsRoute
  '/vulnerabilities': typeof VulnerabilitiesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blast-radius': typeof BlastRadiusRoute
  '/dependencies': typeof DependenciesRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/remediation': typeof RemediationRoute
  '/reports': typeof ReportsRoute
  '/repositories': typeof RepositoriesRoute
  '/sbom': typeof SbomRoute
  '/settings': typeof SettingsRoute
  '/vulnerabilities': typeof VulnerabilitiesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blast-radius': typeof BlastRadiusRoute
  '/dependencies': typeof DependenciesRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/remediation': typeof RemediationRoute
  '/reports': typeof ReportsRoute
  '/repositories': typeof RepositoriesRoute
  '/sbom': typeof SbomRoute
  '/settings': typeof SettingsRoute
  '/vulnerabilities': typeof VulnerabilitiesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blast-radius'
    | '/dependencies'
    | '/insights'
    | '/login'
    | '/remediation'
    | '/reports'
    | '/repositories'
    | '/sbom'
    | '/settings'
    | '/vulnerabilities'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blast-radius'
    | '/dependencies'
    | '/insights'
    | '/login'
    | '/remediation'
    | '/reports'
    | '/repositories'
    | '/sbom'
    | '/settings'
    | '/vulnerabilities'
  id:
    | '__root__'
    | '/'
    | '/blast-radius'
    | '/dependencies'
    | '/insights'
    | '/login'
    | '/remediation'
    | '/reports'
    | '/repositories'
    | '/sbom'
    | '/settings'
    | '/vulnerabilities'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlastRadiusRoute: typeof BlastRadiusRoute
  DependenciesRoute: typeof DependenciesRoute
  InsightsRoute: typeof InsightsRoute
  LoginRoute: typeof LoginRoute
  RemediationRoute: typeof RemediationRoute
  ReportsRoute: typeof ReportsRoute
  RepositoriesRoute: typeof RepositoriesRoute
  SbomRoute: typeof SbomRoute
  SettingsRoute: typeof SettingsRoute
  VulnerabilitiesRoute: typeof VulnerabilitiesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blast-radius': {
      id: '/blast-radius'
      path: '/blast-radius'
      fullPath: '/blast-radius'
      preLoaderRoute: typeof BlastRadiusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dependencies': {
      id: '/dependencies'
      path: '/dependencies'
      fullPath: '/dependencies'
      preLoaderRoute: typeof DependenciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remediation': {
      id: '/remediation'
      path: '/remediation'
      fullPath: '/remediation'
      preLoaderRoute: typeof RemediationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repositories': {
      id: '/repositories'
      path: '/repositories'
      fullPath: '/repositories'
      preLoaderRoute: typeof RepositoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sbom': {
      id: '/sbom'
      path: '/sbom'
      fullPath: '/sbom'
      preLoaderRoute: typeof SbomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vulnerabilities': {
      id: '/vulnerabilities'
      path: '/vulnerabilities'
      fullPath: '/vulnerabilities'
      preLoaderRoute: typeof VulnerabilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlastRadiusRoute: BlastRadiusRoute,
  DependenciesRoute: DependenciesRoute,
  InsightsRoute: InsightsRoute,
  LoginRoute: LoginRoute,
  RemediationRoute: RemediationRoute,
  ReportsRoute: ReportsRoute,
  RepositoriesRoute: RepositoriesRoute,
  SbomRoute: SbomRoute,
  SettingsRoute: SettingsRoute,
  VulnerabilitiesRoute: VulnerabilitiesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
