/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlastRadiusRouteImport } from './routes/blast-radius'
import { Route as DependenciesRouteImport } from './routes/dependencies'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RepositoriesRouteImport } from './routes/repositories'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlastRadiusRoute = BlastRadiusRouteImport.update({
  id: '/blast-radius',
  path: '/blast-radius',
  getParentRoute: () => rootRouteImport,
} as any)
const DependenciesRoute = DependenciesRouteImport.update({
  id: '/dependencies',
  path: '/dependencies',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoriesRoute = RepositoriesRouteImport.update({
  id: '/repositories',
  path: '/repositories',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blast-radius': typeof BlastRadiusRoute
  '/dependencies': typeof DependenciesRoute
  '/login': typeof LoginRoute
  '/repositories': typeof RepositoriesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blast-radius': typeof BlastRadiusRoute
  '/dependencies': typeof DependenciesRoute
  '/login': typeof LoginRoute
  '/repositories': typeof RepositoriesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blast-radius': typeof BlastRadiusRoute
  '/dependencies': typeof DependenciesRoute
  '/login': typeof LoginRoute
  '/repositories': typeof RepositoriesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/blast-radius' | '/dependencies' | '/login' | '/repositories'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/blast-radius' | '/dependencies' | '/login' | '/repositories'
  id:
    | '__root__'
    | '/'
    | '/blast-radius'
    | '/dependencies'
    | '/login'
    | '/repositories'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlastRadiusRoute: typeof BlastRadiusRoute
  DependenciesRoute: typeof DependenciesRoute
  LoginRoute: typeof LoginRoute
  RepositoriesRoute: typeof RepositoriesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blast-radius': {
      id: '/blast-radius'
      path: '/blast-radius'
      fullPath: '/blast-radius'
      preLoaderRoute: typeof BlastRadiusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dependencies': {
      id: '/dependencies'
      path: '/dependencies'
      fullPath: '/dependencies'
      preLoaderRoute: typeof DependenciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repositories': {
      id: '/repositories'
      path: '/repositories'
      fullPath: '/repositories'
      preLoaderRoute: typeof RepositoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlastRadiusRoute: BlastRadiusRoute,
  DependenciesRoute: DependenciesRoute,
  LoginRoute: LoginRoute,
  RepositoriesRoute: RepositoriesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
